### ISSUE TITLE
Implement alerting rules for patch-operator

### ISSUE THREAD

**Issue by simu** [projectsyn/component-patch-operator#4]
## Context

Patch-operator exposes metrics (incl. service monitor). The exposed metrics are mostly the standard operator/controller metrics (and go runtime metrics), but there's separate time series for each patch controller which gets created by the operator for the individual Patch resources.

It looks like metrics for different patches get merged if we reuse the same patch identifier in multiple custom resources. In order to get better metrics, we may need to change the component library to use unique patch identifiers.

Additionally, the operator doesn't provide any alerting rules out of the box. We should consider writing some simple alerts that inform us when patches are failing or slow to reconcile. Ideally we should expose this information in a dashboard rather than through alerts, but we don't really have the infrastructure to do so in place yet.

## Alternatives
Don't have alerts and only notice that patches are broken/slow when looking at the operator for some unrelated reason.

**Comment by HappyTetrahedron** [comment]
implemented in #8
